config/routes.rb
Rails.application.routes.draw do
  # match 'users/:id' => 'user#destroy', :via => :delete, :as => :user_destroy

  devise_for :users

  resources :users, only: [:index, :show]
  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user

  resources :searches, only: [:index]

  resources :bars, only: [:index, :show, :create, :edit, :update, :destroy] do
    resources :reviews, only: [:index, :new, :create, :edit, :update, :destroy] do
      post '/up_vote' => 'votes#up_vote', as: :up_vote
      post '/down_vote' => 'votes#down_vote', as: :down_vote
    end
  end

  namespace :api do
    namespace :v1 do
      resources :bars
    end
  end

  root "bars#index"

  namespace :api do
    namespace :v1 do
      resources :bars do
        resources :reviews do
          post '/up_vote' => 'votes#up_vote', as: :up_vote
          post '/down_vote' => 'votes#down_vote', as: :down_vote
        end
      end
    end
  end
end

app/models/bar.rb
class Bar < ApplicationRecord
  has_many :reviews
  belongs_to :user

  validates :name, presence: true
  validates :address, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :zip, presence: true, numericality: true, length: { is: 5 }
  validates :description, length: { maximum: 300 }

  def self.search(term)
    if term
      where('LOWER (name) LIKE ?', "%#{term.downcase}%")
    else
      all
    end
  end
end

app/controllers/api/v1/bars_controller.rb
class Api::V1::BarsController < ApplicationController
  skip_before_filter :verify_authenticity_token

  def index
    @bars = Bar.all
    render json: @bars
  end

  def show
    @bar = Bar.find(params[:id])
    @reviews = @bar.reviews
    @users = []
    @user = current_user
    @reviews.each do |review|
      @users << @user
    end
    render json: {reviews: @reviews, users: @users, currentUser: @user}
  end
end

app/controllers/bars_controller.rb
class BarsController < ApplicationController

  def index
    @bars = Bar.all
    @bar = Bar.new
  end

  def show
    @user = current_user
    @bar = Bar.find(params[:id])
    @reviews = @bar.reviews

    rating = 0
    count = 0
    @bar.reviews.each do |review|
      rating += review.rating
      count += 1
    end

    @average = rating.to_f / count.to_f
  end

  def create
    @user = current_user
    @bar = Bar.new(bar_params)
    @bar.user = current_user

    if @bar.save
      flash[:notice] = "Bar created successfully!"
      redirect_to @bar
    else
      @bars = Bar.all
      flash.now[:notice] = @bar.errors.full_messages.to_sentence
      render :index
    end
  end

  def edit
    @bar = Bar.find(params[:id])
    @user = current_user
    if @user.id == @bar.user_id || @user.admin?
      render :edit
    else
      flash[:notice] = "You don't have permission to edit this bar!"
      redirect_to @bar
    end
  end

  def update
    @bar = Bar.find(params[:id])

    if @bar.update(bar_params)
      redirect_to bar_path
    else
      flash[:notice] = @bar.errors.full_messages.to_sentence
      render :edit
    end
  end

  def destroy
    @bar = Bar.find(params[:id])
    @user = current_user

    if @user.id == @bar.user_id || @user.admin?
      Bar.destroy(params[:id])
      redirect_to bars_path
    else
      flash[:notice] = "You don't have permission to delete this bar!"
      redirect_to @bar
    end
  end

  private

  def bar_params
    params.require(:bar).permit(:name, :address, :city, :state, :zip, :url, :description, :term)
  end

end

app/views/bars/_form.html.erb
<%= form_for(@bar) do |f| %>
  <div class="field">
      <%= f.label :name %><br/>
      <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :address %><br/>
    <%= f.text_field :address %>
  </div>

  <div class="field">
    <%= f.label :city %><br/>
    <%= f.text_field :city %>
  </div>

  <div class="field">
    <%= f.label :state %><br/>
    <%= f.text_field :state %>
  </div>

  <div class="field">
    <%= f.label :zip %><br/>
    <%= f.text_field :zip %>
  </div>

  <div class="field">
    <%= f.label :url %><br/>
    <%= f.text_field :url %>
  </div>

  <div class="field">
    <%= f.label :description %><br/>
    <%= f.text_field :description %>
  </div>

  <div class="actions">
    <%= f.submit(value="Submit") %>
  </div>

<% end %>

app/views/bars/edit.html.erb
<div class="row container">
  <div class="edit-bar columns large-6 small-12">

    <h2>Edit <%= @bar.name %> </h2>

    <%= render 'form' %><br />

    <%= link_to "Delete", @bar, method: :delete, data: {confirm: "Are you sure?"} %>
  </div>
</div>

app/views/bars/index.html.erb
<div class="row container">
  <div class="barlist columns large-6 small-12">
    <div>
      <h3>Get Your Drink On 🍻</h3>
      <div id="BarList">

      </div>

    </div>
  </div>

  <div class="bar-form columns large-6 small-12">
    <h3>New Bar Form</h3>
    <%= form_for(@bar) do |f| %>

    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>

    <div class="field">
      <%= f.label :address %>
      <%= f.text_field :address %>
    </div>

    <div class="field">
      <%= f.label :city %>
      <%= f.text_field :city %>
    </div>

    <div class="field">
      <%= f.label :state %>
      <%= f.text_field :state %>
    </div>

    <div class="field">
      <%= f.label :zip %>
      <%= f.text_field :zip %>
    </div>

    <div class="field">
      <%= f.label :url %>
      <%= f.text_field :url %>
    </div>

    <div class="field">
      <%= f.label :description %>
      <%= f.text_field :description %>
    </div>

    <div class="actions">
      <%= f.submit(value="Add Bar") %>
    </div>

    <% end %>
  </div>
</div>

app/views/bars/show.html.erb
<div class="row container">
  <div class="columns large-6 small-12">

    <% if @average.to_f.round(1).nan? %>
      <h3>Not Yet Rated </h3>
    <% else %>
      <h3>Rating: <%= @average.to_f.round(1) %> </h3>
    <% end %>
    <% if @bar.user %>
      <p class="created-by">Created by <%= @bar.user.username %></p>
    <% end %>

<br />
<div class="bar-show-details">
  <h1> <%= @bar.name %> </h1>

    <div class="bar-details">
      <p> <%= @bar.address %> </p>
      <p> <%= @bar.city %>, <%= @bar.state %>, <%= @bar.zip %> </p>
    </div>

    <div class="bar-details">
      <% unless @bar.description.nil? %>
        <p> <%= @bar.description %> </p>
      <% end %>
      <% unless @bar.url.nil? %>
        <p> <%= link_to "#{@bar.url}", "#{@bar.url}" %>
      <% end %>
    </div>
  </div>
</div>



  <div class="barlist columns large-6 small-12">
    <div>
      <%= image_tag("beer.jpg") %>
    </div>
  </div>

<% if @user.id == @bar.user_id || @user.admin? %>
  <div>
    <%= link_to 'Edit Bar', edit_bar_path(@bar) %>
  </div>
<% end %>


<div id="ReviewList"></div>


<div>
  <%= link_to "Add Review", new_bar_review_path(@bar) %>
</div>