config/routes.rb
Rails.application.routes.draw do
  # match 'users/:id' => 'user#destroy', :via => :delete, :as => :user_destroy

  devise_for :users

  resources :users, only: [:index, :show]
  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user

  resources :searches, only: [:index]

  resources :bars, only: [:index, :show, :create, :edit, :update, :destroy] do
    resources :reviews, only: [:index, :new, :create, :edit, :update, :destroy] do
      post '/up_vote' => 'votes#up_vote', as: :up_vote
      post '/down_vote' => 'votes#down_vote', as: :down_vote
    end
  end

  namespace :api do
    namespace :v1 do
      resources :bars
    end
  end

  root "bars#index"

  namespace :api do
    namespace :v1 do
      resources :bars do
        resources :reviews do
          post '/up_vote' => 'votes#up_vote', as: :up_vote
          post '/down_vote' => 'votes#down_vote', as: :down_vote
        end
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :bars
  has_many :votes

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :username, presence: true, uniqueness: true
  validates :email, presence: true

  has_many :bars

  mount_uploader :avatar, AvatarUploader

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_action :configure_sign_up_params, only: [:create]
# before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  def destroy
    super
  end

  def show
    @user = User.find(params[:id])
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    if !current_user.admin?
      flash[:notice] = "You don't have permission to access this page!"
      redirect_to bars_path
    end
    @users = User.all
  end

  def show
    @user = current_user
  end

  def destroy
    @user = User.find(params[:id])
    if current_user.admin?
      @user.destroy
      redirect_to '/users'
    else
      flash[:notice] = 'You do not have permission to delete users!'
      redirect_to '/'
    end
  end
end

app/views/users/index.html.erb
<h4>Users</h4>

<ul>
  <% @users.each do |user| %>
    <li>
      <%= user.first_name %> <%= user.last_name %> |
      Admin Status: <%= user.admin %> |
      <%= link_to "Delete", admin_destroy_user_path(user), method: :delete, data: { confirm: " Are you sure?" }, id: "#{user.id}" %>
    </li>
  <% end %>
</ul>

app/views/users/show.html.erb
<div class="row container" id="edit-page">
  <div class="columns large-4 small-12" id="edit-form">
    </br>
    <h3><%= @user.first_name %> <%= @user.last_name %></h3>
    <li>Username: <%= @user.username %></li>
    <li>Email: <%= @user.email %></li>
    <br/>

    <h4>Bars Created:</h4>
    <% unless @user.bars.empty? %>
      <ul>
        <% @user.bars.each do |bar| %>
          <li><%= link_to "#{bar.name}", "/bars/#{bar.id}" %></li>
        <% end %>
      </ul>
    <% end %>
  </div>

  <div class="columns large-4 small-12" id="edit-form">
    <br/>
    <br/>
    <p class="image"><%= image_tag @user.avatar %></p>
  </div>
</div>